#!/usr/bin/env python3
"""Generate a udev rules template for stable SO-ARM101 device names.

This does not try to guess which physical arm is which. The safe workshop flow is:
1. Plug in one arm at a time.
2. Run scripts/12_snapshot_devices.sh and copy the /dev/serial/by-id fragment.
3. Paste the fragments into configs/arms.yaml under serial_hint.
4. Run this tool to generate a rule file.
5. Review it, then install it with sudo.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

import yaml


def sanitize(value: str) -> str:
    value = value.strip()
    value = value.replace("/dev/serial/by-id/", "")
    value = value.replace("/dev/", "")
    return value


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/arms.yaml")
    parser.add_argument("--out", default="99-so101-workshop.rules")
    args = parser.parse_args()

    cfg = yaml.safe_load(Path(args.config).read_text())
    lines = [
        '# Generated by tools/generate_udev_rules.py',
        '# Review before installing:',
        '#   sudo cp 99-so101-workshop.rules /etc/udev/rules.d/',
        '#   sudo udevadm control --reload-rules && sudo udevadm trigger',
        '#',
    ]
    missing: list[str] = []

    for rig_name, rig in sorted(cfg.get("rigs", {}).items()):
        for role in ("follower", "leader"):
            arm = rig[role]
            hint = sanitize(str(arm.get("serial_hint", "")))
            port = str(arm.get("port", ""))
            match = re.match(r"/dev/so101/(.+)", port)
            if not hint or "paste " in hint:
                missing.append(f"{rig_name}.{role}")
                continue
            if not match:
                missing.append(f"{rig_name}.{role} has non-/dev/so101 port {port}")
                continue
            symlink = f"so101/{match.group(1)}"
            # Match by the by-id symlink name. This is easier to maintain for teachers than ATTRS chains.
            lines.append(
                f'SUBSYSTEM=="tty", ENV{{ID_SERIAL}}=="*{hint}*", '
                f'SYMLINK+="{symlink}", GROUP="dialout", MODE="0660"'
            )

    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"Wrote {args.out}")
    if missing:
        print("\nMissing or incomplete serial_hint entries:")
        for item in missing:
            print(f"  - {item}")
        print("\nPlug in one arm at a time, run scripts/12_snapshot_devices.sh, then update configs/arms.yaml.")


if __name__ == "__main__":
    main()
