#!/usr/bin/env python3
"""Guided local setup for one SO-ARM101 leader/follower station."""
from __future__ import annotations

import argparse
import grp
import os
import pwd
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml


def run(cmd: list[str], *, check: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=check)


def serial_hint_to_id(hint: str) -> str:
    value = hint.strip().replace("/dev/serial/by-id/", "").replace("/dev/", "")
    if value.startswith("usb-"):
        value = value.removeprefix("usb-")
    if value.endswith("-if00"):
        value = value.removesuffix("-if00")
    return value


def by_id_devices() -> dict[str, Path]:
    base = Path("/dev/serial/by-id")
    if not base.exists():
        return {}
    return {item.name: item for item in sorted(base.iterdir())}


def find_device(serial_hint: str) -> Path | None:
    needle = serial_hint_to_id(serial_hint)
    for name, path in by_id_devices().items():
        if needle in name or needle in serial_hint_to_id(name):
            return path
    return None


def set_arm(cfg: dict[str, Any], rig: str, role: str, serial: str) -> None:
    cfg["rigs"][rig][role]["serial_hint"] = serial


def load_config(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Missing {path}")
    return yaml.safe_load(path.read_text())


def update_serial_hint_text(path: Path, rig: str, role: str, serial: str) -> None:
    """Update one serial_hint while preserving comments and most formatting."""
    lines = path.read_text().splitlines()
    in_rig = False
    in_role = False
    rig_indent = role_indent = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        indent = len(line) - len(line.lstrip(" "))
        if stripped == f"{rig}:":
            in_rig = True
            in_role = False
            rig_indent = indent
            continue
        if in_rig and indent <= rig_indent and stripped and not line.lstrip().startswith("#"):
            in_rig = False
            in_role = False
        if in_rig and stripped == f"{role}:":
            in_role = True
            role_indent = indent
            continue
        if in_role and indent <= role_indent and stripped and not line.lstrip().startswith("#"):
            in_role = False
        if in_role and stripped.startswith("serial_hint:"):
            prefix = line[: indent]
            lines[i] = f'{prefix}serial_hint: "{serial}"'
            path.write_text("\n".join(lines) + "\n")
            return
    raise ValueError(f"Could not find {rig}.{role}.serial_hint in {path}")


def write_env(path: Path, rig: str, follower: Path, leader: Path, cfg: dict[str, Any]) -> None:
    rig_cfg = cfg["rigs"][rig]
    camera = "{ front: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}"
    dataset = f"hs-so101-{rig}-cube-sort"
    task_text = rig_cfg.get("task_text", "Pick up the cube and place it in the bin")
    path.write_text(
        "\n".join(
            [
                f"RIG={rig}",
                "ARMS_CONFIG=configs/arms.yaml",
                "",
                "# Generated by tools/setup_rig.py.",
                "# Uses stable /dev/serial/by-id paths until /dev/so101 udev links are installed.",
                f"FOLLOWER_PORT={follower}",
                f"LEADER_PORT={leader}",
                f"FOLLOWER_ID={rig_cfg['follower']['id']}",
                f"LEADER_ID={rig_cfg['leader']['id']}",
                f'CAMERA_CONFIG="{camera}"',
                "",
                "HF_USER=your-hf-user",
                f"DATASET_NAME={dataset}",
                f'TASK_TEXT="{task_text}"',
                "",
            ]
        )
    )


def check_dialout() -> tuple[bool, str]:
    user = pwd.getpwuid(os.getuid()).pw_name
    groups = {grp.getgrgid(gid).gr_name for gid in os.getgroups()}
    if "dialout" in groups:
        return True, f"{user} is in dialout"
    return False, f"{user} is not in dialout"


def install_udev(rule_path: Path) -> bool:
    target = Path("/etc/udev/rules.d") / rule_path.name
    if shutil.which("sudo") is None:
        print("sudo is not available; skipping udev install.")
        return False
    commands = [
        ["sudo", "-n", "cp", str(rule_path), str(target)],
        ["sudo", "-n", "udevadm", "control", "--reload-rules"],
        ["sudo", "-n", "udevadm", "trigger"],
    ]
    for cmd in commands:
        proc = run(cmd)
        if proc.returncode != 0:
            print(f"Could not run: {' '.join(cmd)}")
            print(proc.stdout.strip())
            print("Run the printed sudo commands manually, then unplug/replug both arms.")
            return False
    print(f"Installed {target}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Set up one SO-ARM101 rig from known USB serial devices.")
    parser.add_argument("--config", default="configs/arms.yaml")
    parser.add_argument("--rig", default="rig01")
    parser.add_argument("--leader-serial", help="Leader USB serial/by-id name or serial fragment")
    parser.add_argument("--follower-serial", help="Follower/base USB serial/by-id name or serial fragment")
    parser.add_argument("--env-out", default="configs/arms.env")
    parser.add_argument("--rules-out", default="99-so101-workshop.rules")
    parser.add_argument("--install-udev", action="store_true", help="Install generated udev rules with sudo -n")
    args = parser.parse_args()

    cfg_path = Path(args.config)
    cfg = load_config(cfg_path)
    if args.rig not in cfg.get("rigs", {}):
        valid = ", ".join(sorted(cfg.get("rigs", {})))
        print(f"Unknown rig {args.rig!r}. Valid rigs: {valid}", file=sys.stderr)
        return 2

    rig_cfg = cfg["rigs"][args.rig]
    if args.follower_serial:
        set_arm(cfg, args.rig, "follower", args.follower_serial)
    if args.leader_serial:
        set_arm(cfg, args.rig, "leader", args.leader_serial)

    follower = find_device(rig_cfg["follower"].get("serial_hint", ""))
    leader = find_device(rig_cfg["leader"].get("serial_hint", ""))

    print("# SO-ARM101 rig setup")
    print()
    print("Detected serial devices:")
    devices = by_id_devices()
    if devices:
        for name, path in devices.items():
            print(f"  {name} -> {path.resolve()}")
    else:
        print("  <none>")
    print()

    if follower is None or leader is None:
        print("Could not match both arms from configs/arms.yaml.")
        print("Run lerobot-find-port once for each arm, then rerun with:")
        print(
            "  python tools/setup_rig.py "
            "--follower-serial <follower-by-id-or-serial> "
            "--leader-serial <leader-by-id-or-serial>"
        )
        return 1

    print(f"{args.rig} mapping:")
    print(f"  follower/base -> {follower} -> {follower.resolve()}")
    print(f"  leader        -> {leader} -> {leader.resolve()}")
    print()

    if args.follower_serial:
        update_serial_hint_text(cfg_path, args.rig, "follower", args.follower_serial)
    if args.leader_serial:
        update_serial_hint_text(cfg_path, args.rig, "leader", args.leader_serial)
    write_env(Path(args.env_out), args.rig, follower, leader, cfg)
    print(f"Updated {cfg_path}")
    print(f"Wrote {args.env_out}")

    proc = run(["python", "tools/generate_udev_rules.py", "--config", str(cfg_path), "--out", args.rules_out])
    print(proc.stdout.strip())

    ok, msg = check_dialout()
    print(msg)
    if not ok:
        user = pwd.getpwuid(os.getuid()).pw_name
        print(f"Run: sudo bash scripts/15_install_linux_permissions.sh {user}")
        print("Then log out and back in before calibrating.")

    if args.install_udev:
        install_udev(Path(args.rules_out))
    else:
        print("To install stable /dev/so101 links, run:")
        print(f"  sudo bash scripts/15_install_linux_permissions.sh {pwd.getpwuid(os.getuid()).pw_name}")
        print("  unplug/replug both arms")

    print()
    print("Next commands after permissions are fixed:")
    print("  bash scripts/01_calibrate_follower.sh")
    print("  bash scripts/02_calibrate_leader.sh")
    print("  bash scripts/03_teleop_wow.sh")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
